"""Initial schema

Revision ID: 0673f9c9e382
Revises: None
Create Date: 2026-06-04 11:21:23.539687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0673f9c9e382'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_action'), 'audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_entries_id'), 'audit_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entries_patient_id'), 'audit_entries', ['patient_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('qualifications', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('doctor_role', sa.String(length=100), nullable=True, comment='Medical Oncologist, Hematologist, etc.'),
    sa.Column('max_new_consults_per_day', sa.Integer(), nullable=True),
    sa.Column('max_follow_ups_per_day', sa.Integer(), nullable=True),
    sa.Column('max_working_hours', sa.Integer(), nullable=True),
    sa.Column('max_urgent_cases_per_day', sa.Integer(), nullable=True),
    sa.Column('accepts_new_patients', sa.Boolean(), nullable=False),
    sa.Column('accepts_emergency', sa.Boolean(), nullable=False),
    sa.Column('accepts_second_opinions', sa.Boolean(), nullable=False),
    sa.Column('accepts_rare_cancers', sa.Boolean(), nullable=False),
    sa.Column('accepts_pediatric', sa.Boolean(), nullable=False),
    sa.Column('accepts_clinical_trial_referrals', sa.Boolean(), nullable=False),
    sa.Column('telemedicine_available', sa.Boolean(), nullable=False),
    sa.Column('appointment_durations', sa.JSON(), nullable=True, comment='{"new_consult": 60, "followup": 15}'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=500), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.Column('patient_comments', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('role_document_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'RECEPTIONIST', 'NURSE', 'PATIENT', name='role'), nullable=False),
    sa.Column('document_type', sa.Enum('GOVERNMENT_ID', 'MEDICAL_LICENSE', 'DEGREE_CERTIFICATE', 'CV', 'BOARD_CERTIFICATION', 'NURSING_LICENSE', 'EXPERIENCE_LETTER', 'EMPLOYMENT_AGREEMENT', name='documenttype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_document_requirements_id'), 'role_document_requirements', ['id'], unique=False)
    op.create_table('slot_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_availabilities_id'), 'slot_availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_slot_availabilities_start_time'), 'slot_availabilities', ['start_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'RECEPTIONIST', 'NURSE', 'PATIENT', name='role'), nullable=False),
    sa.Column('verification_status', sa.Enum('INVITED', 'PROFILE_INCOMPLETE', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='verificationstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('fhir_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('doctor_case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_case_studies_doctor_id'), 'doctor_case_studies', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_case_studies_id'), 'doctor_case_studies', ['id'], unique=False)
    op.create_table('doctor_clinical_trial_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('trial_topic', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_clinical_trial_interests_doctor_id'), 'doctor_clinical_trial_interests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_clinical_trial_interests_id'), 'doctor_clinical_trial_interests', ['id'], unique=False)
    op.create_table('doctor_disease_expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('disease_type', sa.String(length=150), nullable=False, comment='E.g., Breast Cancer, AML'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Oncology, Hematology'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_disease_expertise_doctor_id'), 'doctor_disease_expertise', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_disease_expertise_id'), 'doctor_disease_expertise', ['id'], unique=False)
    op.create_table('doctor_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('clinic_room', sa.String(length=100), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_locations_doctor_id'), 'doctor_locations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_locations_id'), 'doctor_locations', ['id'], unique=False)
    op.create_table('doctor_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_permissions_doctor_id'), 'doctor_permissions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_permissions_id'), 'doctor_permissions', ['id'], unique=False)
    op.create_table('doctor_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('journal', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_publications_doctor_id'), 'doctor_publications', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_publications_id'), 'doctor_publications', ['id'], unique=False)
    op.create_table('doctor_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('reference_name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_references_doctor_id'), 'doctor_references', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_references_id'), 'doctor_references', ['id'], unique=False)
    op.create_table('doctor_routing_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('active_cases', sa.Integer(), nullable=True),
    sa.Column('avg_wait_days', sa.Float(), nullable=True),
    sa.Column('avg_consult_duration', sa.Integer(), nullable=True),
    sa.Column('urgent_case_capacity_remaining', sa.Integer(), nullable=True),
    sa.Column('accepting_new_patients', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctor_routing_profiles_id'), 'doctor_routing_profiles', ['id'], unique=False)
    op.create_table('doctor_schedule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='E.g., Vacation, Medical Leave'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedule_exceptions_doctor_id'), 'doctor_schedule_exceptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedule_exceptions_id'), 'doctor_schedule_exceptions', ['id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_id'), 'doctor_schedules', ['id'], unique=False)
    op.create_table('doctor_time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_time_off_doctor_id'), 'doctor_time_off', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_time_off_id'), 'doctor_time_off', ['id'], unique=False)
    op.create_table('doctor_treatment_expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_treatment_expertise_doctor_id'), 'doctor_treatment_expertise', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_treatment_expertise_id'), 'doctor_treatment_expertise', ['id'], unique=False)
    op.create_table('doctor_tumor_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_tumor_boards_doctor_id'), 'doctor_tumor_boards', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_tumor_boards_id'), 'doctor_tumor_boards', ['id'], unique=False)
    op.create_table('insurance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=150), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('group_number', sa.String(length=100), nullable=True),
    sa.Column('request_type', sa.String(length=100), nullable=True),
    sa.Column('auth_status', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_records_id'), 'insurance_records', ['id'], unique=False)
    op.create_table('oncology_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('referral_letter', sa.JSON(), nullable=True),
    sa.Column('pathology_report', sa.JSON(), nullable=True),
    sa.Column('imaging_report', sa.JSON(), nullable=True),
    sa.Column('insurance_authorization', sa.JSON(), nullable=True),
    sa.Column('intake_status', sa.String(length=50), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_oncology_intakes_id'), 'oncology_intakes', ['id'], unique=False)
    op.create_table('staff_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('GOVERNMENT_ID', 'MEDICAL_LICENSE', 'DEGREE_CERTIFICATE', 'CV', 'BOARD_CERTIFICATION', 'NURSING_LICENSE', 'EXPERIENCE_LETTER', 'EMPLOYMENT_AGREEMENT', name='documenttype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'REQUIRES_UPDATE', name='documentstatus'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_documents_id'), 'staff_documents', ['id'], unique=False)
    op.create_index(op.f('ix_staff_documents_user_id'), 'staff_documents', ['user_id'], unique=False)
    op.create_table('infusion_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infusion_schedules_id'), 'infusion_schedules', ['id'], unique=False)
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('REFERRAL_LETTER', 'PATHOLOGY_REPORT', 'IMAGING_REPORT', 'INSURANCE_AUTHORIZATION', 'CBC_REPORT', 'CMP_REPORT', 'MEDICATION_LIST', 'ALLERGY_RECORD', 'CONSULTATION_NOTE', 'NURSING_NOTE', 'SURGERY_REPORT', 'DISCHARGE_SUMMARY', 'RADIATION_REPORT', name='documenttype'), nullable=False),
    sa.Column('phase', sa.Enum('PHASE_1', 'PHASE_2', 'PHASE_3', name='intakephase'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['oncology_intakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_documents_id'), 'uploaded_documents', ['id'], unique=False)
    op.create_table('chair_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['infusion_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chair_assignments_id'), 'chair_assignments', ['id'], unique=False)
    op.create_table('completeness_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('missing_sections', sa.JSON(), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completeness_checks_id'), 'completeness_checks', ['id'], unique=False)
    op.create_table('nurse_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['infusion_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_assignments_id'), 'nurse_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nurse_assignments_id'), table_name='nurse_assignments')
    op.drop_table('nurse_assignments')
    op.drop_index(op.f('ix_completeness_checks_id'), table_name='completeness_checks')
    op.drop_table('completeness_checks')
    op.drop_index(op.f('ix_chair_assignments_id'), table_name='chair_assignments')
    op.drop_table('chair_assignments')
    op.drop_index(op.f('ix_uploaded_documents_id'), table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    op.drop_index(op.f('ix_infusion_schedules_id'), table_name='infusion_schedules')
    op.drop_table('infusion_schedules')
    op.drop_index(op.f('ix_staff_documents_user_id'), table_name='staff_documents')
    op.drop_index(op.f('ix_staff_documents_id'), table_name='staff_documents')
    op.drop_table('staff_documents')
    op.drop_index(op.f('ix_oncology_intakes_id'), table_name='oncology_intakes')
    op.drop_table('oncology_intakes')
    op.drop_index(op.f('ix_insurance_records_id'), table_name='insurance_records')
    op.drop_table('insurance_records')
    op.drop_index(op.f('ix_doctor_tumor_boards_id'), table_name='doctor_tumor_boards')
    op.drop_index(op.f('ix_doctor_tumor_boards_doctor_id'), table_name='doctor_tumor_boards')
    op.drop_table('doctor_tumor_boards')
    op.drop_index(op.f('ix_doctor_treatment_expertise_id'), table_name='doctor_treatment_expertise')
    op.drop_index(op.f('ix_doctor_treatment_expertise_doctor_id'), table_name='doctor_treatment_expertise')
    op.drop_table('doctor_treatment_expertise')
    op.drop_index(op.f('ix_doctor_time_off_id'), table_name='doctor_time_off')
    op.drop_index(op.f('ix_doctor_time_off_doctor_id'), table_name='doctor_time_off')
    op.drop_table('doctor_time_off')
    op.drop_index(op.f('ix_doctor_schedules_id'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedule_exceptions_id'), table_name='doctor_schedule_exceptions')
    op.drop_index(op.f('ix_doctor_schedule_exceptions_doctor_id'), table_name='doctor_schedule_exceptions')
    op.drop_table('doctor_schedule_exceptions')
    op.drop_index(op.f('ix_doctor_routing_profiles_id'), table_name='doctor_routing_profiles')
    op.drop_table('doctor_routing_profiles')
    op.drop_index(op.f('ix_doctor_references_id'), table_name='doctor_references')
    op.drop_index(op.f('ix_doctor_references_doctor_id'), table_name='doctor_references')
    op.drop_table('doctor_references')
    op.drop_index(op.f('ix_doctor_publications_id'), table_name='doctor_publications')
    op.drop_index(op.f('ix_doctor_publications_doctor_id'), table_name='doctor_publications')
    op.drop_table('doctor_publications')
    op.drop_index(op.f('ix_doctor_permissions_id'), table_name='doctor_permissions')
    op.drop_index(op.f('ix_doctor_permissions_doctor_id'), table_name='doctor_permissions')
    op.drop_table('doctor_permissions')
    op.drop_index(op.f('ix_doctor_locations_id'), table_name='doctor_locations')
    op.drop_index(op.f('ix_doctor_locations_doctor_id'), table_name='doctor_locations')
    op.drop_table('doctor_locations')
    op.drop_index(op.f('ix_doctor_disease_expertise_id'), table_name='doctor_disease_expertise')
    op.drop_index(op.f('ix_doctor_disease_expertise_doctor_id'), table_name='doctor_disease_expertise')
    op.drop_table('doctor_disease_expertise')
    op.drop_index(op.f('ix_doctor_clinical_trial_interests_id'), table_name='doctor_clinical_trial_interests')
    op.drop_index(op.f('ix_doctor_clinical_trial_interests_doctor_id'), table_name='doctor_clinical_trial_interests')
    op.drop_table('doctor_clinical_trial_interests')
    op.drop_index(op.f('ix_doctor_case_studies_id'), table_name='doctor_case_studies')
    op.drop_index(op.f('ix_doctor_case_studies_doctor_id'), table_name='doctor_case_studies')
    op.drop_table('doctor_case_studies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slot_availabilities_start_time'), table_name='slot_availabilities')
    op.drop_index(op.f('ix_slot_availabilities_id'), table_name='slot_availabilities')
    op.drop_table('slot_availabilities')
    op.drop_index(op.f('ix_role_document_requirements_id'), table_name='role_document_requirements')
    op.drop_table('role_document_requirements')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_audit_entries_patient_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_action'), table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
