"""enterprise doctor tables

Revision ID: 1efe412704a7
Revises: c49e328abe36
Create Date: 2026-06-03 15:58:06.641093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1efe412704a7'
down_revision: Union[str, None] = 'c49e328abe36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_clinical_trial_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('trial_topic', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_clinical_trial_interests_doctor_id'), 'doctor_clinical_trial_interests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_clinical_trial_interests_id'), 'doctor_clinical_trial_interests', ['id'], unique=False)
    op.create_table('doctor_disease_expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('disease_type', sa.String(length=150), nullable=False, comment='E.g., Breast Cancer, AML'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Oncology, Hematology'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_disease_expertise_doctor_id'), 'doctor_disease_expertise', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_disease_expertise_id'), 'doctor_disease_expertise', ['id'], unique=False)
    op.create_table('doctor_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('clinic_room', sa.String(length=100), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_locations_doctor_id'), 'doctor_locations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_locations_id'), 'doctor_locations', ['id'], unique=False)
    op.create_table('doctor_routing_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('active_cases', sa.Integer(), nullable=True),
    sa.Column('avg_wait_days', sa.Float(), nullable=True),
    sa.Column('avg_consult_duration', sa.Integer(), nullable=True),
    sa.Column('urgent_case_capacity_remaining', sa.Integer(), nullable=True),
    sa.Column('accepting_new_patients', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctor_routing_profiles_id'), 'doctor_routing_profiles', ['id'], unique=False)
    op.create_table('doctor_schedule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='E.g., Vacation, Medical Leave'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedule_exceptions_doctor_id'), 'doctor_schedule_exceptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedule_exceptions_id'), 'doctor_schedule_exceptions', ['id'], unique=False)
    op.create_table('doctor_treatment_expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_treatment_expertise_doctor_id'), 'doctor_treatment_expertise', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_treatment_expertise_id'), 'doctor_treatment_expertise', ['id'], unique=False)
    op.create_table('doctor_tumor_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_tumor_boards_doctor_id'), 'doctor_tumor_boards', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_tumor_boards_id'), 'doctor_tumor_boards', ['id'], unique=False)
    op.drop_index(op.f('ix_doctor_time_off_doctor_id'), table_name='doctor_time_off')
    op.drop_index(op.f('ix_doctor_time_off_id'), table_name='doctor_time_off')
    op.drop_table('doctor_time_off')
    op.add_column('doctor_schedules', sa.Column('location', sa.String(length=255), nullable=True))
    op.alter_column('doctor_schedules', 'day_of_week',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0=Monday, 1=Tuesday, ..., 6=Sunday. NULL if specific_date is set.',
               existing_nullable=True)
    op.alter_column('doctor_schedules', 'specific_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Set for one-off schedule overrides. NULL for recurring weekly schedules.',
               existing_nullable=True)
    op.add_column('doctors', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('profile_photo', sa.String(length=500), nullable=True))
    op.add_column('doctors', sa.Column('qualifications', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('license_number', sa.String(length=100), nullable=True))
    op.add_column('doctors', sa.Column('doctor_role', sa.String(length=100), nullable=True, comment='Medical Oncologist, Hematologist, etc.'))
    op.add_column('doctors', sa.Column('max_new_consults_per_day', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('max_follow_ups_per_day', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('max_working_hours', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('max_urgent_cases_per_day', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('accepts_new_patients', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('accepts_emergency', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('accepts_second_opinions', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('accepts_rare_cancers', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('accepts_pediatric', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('accepts_clinical_trial_referrals', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('telemedicine_available', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('appointment_durations', sa.JSON(), nullable=True, comment='{"new_consult": 60, "followup": 15}'))
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='E.g., Medical Oncology, Radiation Oncology, Surgical Oncology',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(length=150),
               comment='E.g., Medical Oncology, Radiation Oncology, Surgical Oncology',
               existing_nullable=False)
    op.drop_column('doctors', 'appointment_durations')
    op.drop_column('doctors', 'telemedicine_available')
    op.drop_column('doctors', 'accepts_clinical_trial_referrals')
    op.drop_column('doctors', 'accepts_pediatric')
    op.drop_column('doctors', 'accepts_rare_cancers')
    op.drop_column('doctors', 'accepts_second_opinions')
    op.drop_column('doctors', 'accepts_emergency')
    op.drop_column('doctors', 'accepts_new_patients')
    op.drop_column('doctors', 'max_urgent_cases_per_day')
    op.drop_column('doctors', 'max_working_hours')
    op.drop_column('doctors', 'max_follow_ups_per_day')
    op.drop_column('doctors', 'max_new_consults_per_day')
    op.drop_column('doctors', 'doctor_role')
    op.drop_column('doctors', 'license_number')
    op.drop_column('doctors', 'experience_years')
    op.drop_column('doctors', 'qualifications')
    op.drop_column('doctors', 'profile_photo')
    op.drop_column('doctors', 'gender')
    op.alter_column('doctor_schedules', 'specific_date',
               existing_type=sa.DATE(),
               comment='Set for one-off schedule overrides. NULL for recurring weekly schedules.',
               existing_nullable=True)
    op.alter_column('doctor_schedules', 'day_of_week',
               existing_type=sa.INTEGER(),
               comment='0=Monday, 1=Tuesday, ..., 6=Sunday. NULL if specific_date is set.',
               existing_nullable=True)
    op.drop_column('doctor_schedules', 'location')
    op.create_table('doctor_time_off',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_time_off_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_time_off_pkey'))
    )
    op.create_index(op.f('ix_doctor_time_off_id'), 'doctor_time_off', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_time_off_doctor_id'), 'doctor_time_off', ['doctor_id'], unique=False)
    op.drop_index(op.f('ix_doctor_tumor_boards_id'), table_name='doctor_tumor_boards')
    op.drop_index(op.f('ix_doctor_tumor_boards_doctor_id'), table_name='doctor_tumor_boards')
    op.drop_table('doctor_tumor_boards')
    op.drop_index(op.f('ix_doctor_treatment_expertise_id'), table_name='doctor_treatment_expertise')
    op.drop_index(op.f('ix_doctor_treatment_expertise_doctor_id'), table_name='doctor_treatment_expertise')
    op.drop_table('doctor_treatment_expertise')
    op.drop_index(op.f('ix_doctor_schedule_exceptions_id'), table_name='doctor_schedule_exceptions')
    op.drop_index(op.f('ix_doctor_schedule_exceptions_doctor_id'), table_name='doctor_schedule_exceptions')
    op.drop_table('doctor_schedule_exceptions')
    op.drop_index(op.f('ix_doctor_routing_profiles_id'), table_name='doctor_routing_profiles')
    op.drop_table('doctor_routing_profiles')
    op.drop_index(op.f('ix_doctor_locations_id'), table_name='doctor_locations')
    op.drop_index(op.f('ix_doctor_locations_doctor_id'), table_name='doctor_locations')
    op.drop_table('doctor_locations')
    op.drop_index(op.f('ix_doctor_disease_expertise_id'), table_name='doctor_disease_expertise')
    op.drop_index(op.f('ix_doctor_disease_expertise_doctor_id'), table_name='doctor_disease_expertise')
    op.drop_table('doctor_disease_expertise')
    op.drop_index(op.f('ix_doctor_clinical_trial_interests_id'), table_name='doctor_clinical_trial_interests')
    op.drop_index(op.f('ix_doctor_clinical_trial_interests_doctor_id'), table_name='doctor_clinical_trial_interests')
    op.drop_table('doctor_clinical_trial_interests')
    # ### end Alembic commands ###
