"""expand_uploaded_documents_with_phase_and_types

Revision ID: 4f5eb75778e0
Revises: f59c731e2e38
Create Date: 2026-06-02 10:35:44.527210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5eb75778e0'
down_revision: Union[str, None] = 'f59c731e2e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### explicit enum creation for PostgreSQL ###
    intake_phase_enum = postgresql.ENUM('PHASE_1', 'PHASE_2', 'PHASE_3', name='intakephase')
    intake_phase_enum.create(op.get_bind())
    
    document_type_enum = postgresql.ENUM('REFERRAL_LETTER', 'PATHOLOGY_REPORT', 'IMAGING_REPORT', 'INSURANCE_AUTHORIZATION', 'CBC_REPORT', 'CMP_REPORT', 'MEDICATION_LIST', 'ALLERGY_RECORD', 'CONSULTATION_NOTE', 'NURSING_NOTE', 'SURGERY_REPORT', 'DISCHARGE_SUMMARY', 'RADIATION_REPORT', name='documenttype')
    document_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_documents', sa.Column('intake_id', sa.Integer(), nullable=True))
    op.add_column('uploaded_documents', sa.Column('phase', sa.Enum('PHASE_1', 'PHASE_2', 'PHASE_3', name='intakephase'), nullable=False))
    op.add_column('uploaded_documents', sa.Column('file_url', sa.String(length=500), nullable=False))
    op.add_column('uploaded_documents', sa.Column('original_name', sa.String(length=255), nullable=False))
    op.add_column('uploaded_documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.alter_column('uploaded_documents', 'document_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('REFERRAL_LETTER', 'PATHOLOGY_REPORT', 'IMAGING_REPORT', 'INSURANCE_AUTHORIZATION', 'CBC_REPORT', 'CMP_REPORT', 'MEDICATION_LIST', 'ALLERGY_RECORD', 'CONSULTATION_NOTE', 'NURSING_NOTE', 'SURGERY_REPORT', 'DISCHARGE_SUMMARY', 'RADIATION_REPORT', name='documenttype'),
               existing_nullable=False,
               postgresql_using="document_type::text::documenttype")
    op.create_foreign_key(None, 'uploaded_documents', 'oncology_intakes', ['intake_id'], ['id'], ondelete='CASCADE')
    op.drop_column('uploaded_documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'uploaded_documents', type_='foreignkey')
    op.alter_column('uploaded_documents', 'document_type',
               existing_type=sa.Enum('REFERRAL_LETTER', 'PATHOLOGY_REPORT', 'IMAGING_REPORT', 'INSURANCE_AUTHORIZATION', 'CBC_REPORT', 'CMP_REPORT', 'MEDICATION_LIST', 'ALLERGY_RECORD', 'CONSULTATION_NOTE', 'NURSING_NOTE', 'SURGERY_REPORT', 'DISCHARGE_SUMMARY', 'RADIATION_REPORT', name='documenttype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('uploaded_documents', 'uploaded_by')
    op.drop_column('uploaded_documents', 'original_name')
    op.drop_column('uploaded_documents', 'file_url')
    op.drop_column('uploaded_documents', 'phase')
    op.drop_column('uploaded_documents', 'intake_id')
    # ### end Alembic commands ###
