"""Add readiness flags to TreatmentCycle

Revision ID: 5fe30412d7d4
Revises: 9887bb0220e2
Create Date: 2026-06-05 18:55:32.933041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe30412d7d4'
down_revision: Union[str, None] = '9887bb0220e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_cycles', sa.Column('labs_uploaded', sa.Boolean(), nullable=False))
    op.add_column('treatment_cycles', sa.Column('ai_fit_check_passed', sa.Boolean(), nullable=False))
    op.add_column('treatment_cycles', sa.Column('pharmacy_vials_approved', sa.Boolean(), nullable=False))
    op.add_column('treatment_cycles', sa.Column('ready_for_booking', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_cycles', 'ready_for_booking')
    op.drop_column('treatment_cycles', 'pharmacy_vials_approved')
    op.drop_column('treatment_cycles', 'ai_fit_check_passed')
    op.drop_column('treatment_cycles', 'labs_uploaded')
    # ### end Alembic commands ###
