"""final_merged_state

Revision ID: 6541c3e7cd6a
Revises: c49e328abe36
Create Date: 2026-06-04 01:34:40.115230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6541c3e7cd6a'
down_revision: Union[str, None] = 'c49e328abe36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_capacity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('max_new_consults_per_day', sa.Integer(), nullable=False),
    sa.Column('max_follow_ups_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctor_capacity_profiles_id'), 'doctor_capacity_profiles', ['id'], unique=False)
    op.create_table('doctor_time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_time_off_doctor_id'), 'doctor_time_off', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_time_off_id'), 'doctor_time_off', ['id'], unique=False)
    op.drop_index(op.f('ix_doctor_publications_doctor_id'), table_name='doctor_publications')
    op.drop_index(op.f('ix_doctor_publications_id'), table_name='doctor_publications')
    op.drop_table('doctor_publications')
    op.drop_index(op.f('ix_role_document_requirements_id'), table_name='role_document_requirements')
    op.drop_table('role_document_requirements')
    op.drop_index(op.f('ix_doctor_permissions_doctor_id'), table_name='doctor_permissions')
    op.drop_index(op.f('ix_doctor_permissions_id'), table_name='doctor_permissions')
    op.drop_table('doctor_permissions')
    op.drop_index(op.f('ix_doctor_case_studies_doctor_id'), table_name='doctor_case_studies')
    op.drop_index(op.f('ix_doctor_case_studies_id'), table_name='doctor_case_studies')
    op.drop_table('doctor_case_studies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_staff_documents_id'), table_name='staff_documents')
    op.drop_index(op.f('ix_staff_documents_user_id'), table_name='staff_documents')
    op.drop_table('staff_documents')
    op.drop_index(op.f('ix_doctor_references_doctor_id'), table_name='doctor_references')
    op.drop_index(op.f('ix_doctor_references_id'), table_name='doctor_references')
    op.drop_table('doctor_references')
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(length=150),
               comment='E.g., Medical Oncology, Radiation Oncology, Surgical Oncology',
               existing_nullable=False)
    op.alter_column('oncology_intakes', 'ai_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.drop_column('users', 'verification_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_status', postgresql.ENUM('INVITED', 'PROFILE_INCOMPLETE', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='verificationstatus'), server_default=sa.text("'APPROVED'::verificationstatus"), autoincrement=False, nullable=False))
    op.alter_column('oncology_intakes', 'ai_summary',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='E.g., Medical Oncology, Radiation Oncology, Surgical Oncology',
               existing_nullable=False)
    op.create_table('doctor_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_references_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_references_pkey'))
    )
    op.create_index(op.f('ix_doctor_references_id'), 'doctor_references', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_references_doctor_id'), 'doctor_references', ['doctor_id'], unique=False)
    op.create_table('staff_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('REFERRAL_LETTER', 'PATHOLOGY_REPORT', 'IMAGING_REPORT', 'INSURANCE_AUTHORIZATION', 'CBC_REPORT', 'CMP_REPORT', 'MEDICATION_LIST', 'ALLERGY_RECORD', 'CONSULTATION_NOTE', 'NURSING_NOTE', 'SURGERY_REPORT', 'DISCHARGE_SUMMARY', 'RADIATION_REPORT', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'REQUIRES_UPDATE', name='documentstatus'), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('staff_documents_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('staff_documents_verified_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_documents_pkey'))
    )
    op.create_index(op.f('ix_staff_documents_user_id'), 'staff_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_staff_documents_id'), 'staff_documents', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('audit_logs_performed_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('doctor_case_studies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('document_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_case_studies_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_case_studies_pkey'))
    )
    op.create_index(op.f('ix_doctor_case_studies_id'), 'doctor_case_studies', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_case_studies_doctor_id'), 'doctor_case_studies', ['doctor_id'], unique=False)
    op.create_table('doctor_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_permissions_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_permissions_pkey'))
    )
    op.create_index(op.f('ix_doctor_permissions_id'), 'doctor_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_permissions_doctor_id'), 'doctor_permissions', ['doctor_id'], unique=False)
    op.create_table('role_document_requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'DOCTOR', 'RECEPTIONIST', 'NURSE', 'PATIENT', name='role'), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('REFERRAL_LETTER', 'PATHOLOGY_REPORT', 'IMAGING_REPORT', 'INSURANCE_AUTHORIZATION', 'CBC_REPORT', 'CMP_REPORT', 'MEDICATION_LIST', 'ALLERGY_RECORD', 'CONSULTATION_NOTE', 'NURSING_NOTE', 'SURGERY_REPORT', 'DISCHARGE_SUMMARY', 'RADIATION_REPORT', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('role_document_requirements_pkey'))
    )
    op.create_index(op.f('ix_role_document_requirements_id'), 'role_document_requirements', ['id'], unique=False)
    op.create_table('doctor_publications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('journal', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_publications_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_publications_pkey'))
    )
    op.create_index(op.f('ix_doctor_publications_id'), 'doctor_publications', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_publications_doctor_id'), 'doctor_publications', ['doctor_id'], unique=False)
    op.drop_index(op.f('ix_doctor_time_off_id'), table_name='doctor_time_off')
    op.drop_index(op.f('ix_doctor_time_off_doctor_id'), table_name='doctor_time_off')
    op.drop_table('doctor_time_off')
    op.drop_index(op.f('ix_doctor_capacity_profiles_id'), table_name='doctor_capacity_profiles')
    op.drop_table('doctor_capacity_profiles')
    # ### end Alembic commands ###
