"""add extracted_text

Revision ID: 708c2e189e7f
Revises: 6541c3e7cd6a
Create Date: 2026-06-04 13:16:42.371075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708c2e189e7f'
down_revision: Union[str, None] = '6541c3e7cd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(length=150),
               comment='E.g., Medical Oncology, Radiation Oncology, Surgical Oncology',
               existing_nullable=False)
    op.add_column('uploaded_documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_documents', 'extracted_text')
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='E.g., Medical Oncology, Radiation Oncology, Surgical Oncology',
               existing_nullable=False)
    # ### end Alembic commands ###
