"""add prescription_notes

Revision ID: 72bdfc6dc429
Revises: 085f6db35ecc
Create Date: 2026-06-05 13:32:23.261658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72bdfc6dc429'
down_revision: Union[str, None] = '085f6db35ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('prescription_notes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'prescription_notes')
    # ### end Alembic commands ###
