"""Add appointment_id to TreatmentPlan

Revision ID: 9887bb0220e2
Revises: 8249f29e97d8
Create Date: 2026-06-05 18:45:16.147832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9887bb0220e2'
down_revision: Union[str, None] = '8249f29e97d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_plans', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'treatment_plans', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment_plans', type_='foreignkey')
    op.drop_column('treatment_plans', 'appointment_id')
    # ### end Alembic commands ###
