"""Add experience and qualifications

Revision ID: c48b18257b09
Revises: 62f15c887685
Create Date: 2026-06-03 16:55:19.887366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48b18257b09'
down_revision: Union[str, None] = '62f15c887685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('qualifications', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'qualifications')
    op.drop_column('doctors', 'experience_years')
    # ### end Alembic commands ###
