"""add insurance columns

Revision ID: c49e328abe36
Revises: 4f5eb75778e0
Create Date: 2026-06-03 12:28:33.508230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49e328abe36'
down_revision: Union[str, None] = '4f5eb75778e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_records', sa.Column('request_type', sa.String(length=100), nullable=True))
    op.add_column('insurance_records', sa.Column('auth_status', sa.String(length=50), nullable=True))
    op.add_column('insurance_records', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_records', 'expiry_date')
    op.drop_column('insurance_records', 'auth_status')
    op.drop_column('insurance_records', 'request_type')
    # ### end Alembic commands ###
