"""Add OncologyIntake and Patient fields

Revision ID: f59c731e2e38
Revises: 8557cb963f08
Create Date: 2026-06-01 17:23:57.081858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59c731e2e38'
down_revision: Union[str, None] = '8557cb963f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oncology_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('referral_letter', sa.JSON(), nullable=True),
    sa.Column('pathology_report', sa.JSON(), nullable=True),
    sa.Column('imaging_report', sa.JSON(), nullable=True),
    sa.Column('insurance_authorization', sa.JSON(), nullable=True),
    sa.Column('intake_status', sa.String(length=50), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_oncology_intakes_id'), 'oncology_intakes', ['id'], unique=False)
    op.add_column('patients', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'gender')
    op.drop_index(op.f('ix_oncology_intakes_id'), table_name='oncology_intakes')
    op.drop_table('oncology_intakes')
    # ### end Alembic commands ###
