"""Add Treatment Journey models Phase A

Revision ID: f7258259925e
Revises: 8249f29e97d8
Create Date: 2026-06-06 12:01:02.875310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7258259925e'
down_revision: Union[str, None] = '8249f29e97d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_rules_id'), 'safety_rules', ['id'], unique=False)
    op.create_table('staff_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_availabilities_date'), 'staff_availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_staff_availabilities_id'), 'staff_availabilities', ['id'], unique=False)
    op.create_table('staff_capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_patients_per_shift', sa.Integer(), nullable=False),
    sa.Column('max_infusion_patients', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_capacities_id'), 'staff_capacities', ['id'], unique=False)
    op.create_table('treatment_cycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['treatment_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_cycle_events_id'), 'treatment_cycle_events', ['id'], unique=False)
    op.add_column('treatment_cycles', sa.Column('planned_date', sa.Date(), nullable=True))
    op.add_column('treatment_cycles', sa.Column('completed_date', sa.Date(), nullable=True))
    op.add_column('treatment_cycles', sa.Column('delay_reason', sa.String(length=500), nullable=True))
    op.add_column('treatment_cycles', sa.Column('delayed_days', sa.Integer(), nullable=True))
    op.drop_column('treatment_cycles', 'pharmacy_vials_approved')
    op.drop_column('treatment_cycles', 'ready_for_booking')
    op.drop_column('treatment_cycles', 'labs_uploaded')
    op.drop_column('treatment_cycles', 'ai_fit_check_passed')
    op.drop_constraint(op.f('treatment_plans_appointment_id_fkey'), 'treatment_plans', type_='foreignkey')
    op.drop_column('treatment_plans', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_plans', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('treatment_plans_appointment_id_fkey'), 'treatment_plans', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.add_column('treatment_cycles', sa.Column('ai_fit_check_passed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('treatment_cycles', sa.Column('labs_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('treatment_cycles', sa.Column('ready_for_booking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('treatment_cycles', sa.Column('pharmacy_vials_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('treatment_cycles', 'delayed_days')
    op.drop_column('treatment_cycles', 'delay_reason')
    op.drop_column('treatment_cycles', 'completed_date')
    op.drop_column('treatment_cycles', 'planned_date')
    op.drop_index(op.f('ix_treatment_cycle_events_id'), table_name='treatment_cycle_events')
    op.drop_table('treatment_cycle_events')
    op.drop_index(op.f('ix_staff_capacities_id'), table_name='staff_capacities')
    op.drop_table('staff_capacities')
    op.drop_index(op.f('ix_staff_availabilities_id'), table_name='staff_availabilities')
    op.drop_index(op.f('ix_staff_availabilities_date'), table_name='staff_availabilities')
    op.drop_table('staff_availabilities')
    op.drop_index(op.f('ix_safety_rules_id'), table_name='safety_rules')
    op.drop_table('safety_rules')
    # ### end Alembic commands ###
