"""add infusion chair and treatment plan fields

Revision ID: f790719f3f1c
Revises: 72bdfc6dc429
Create Date: 2026-06-05 15:09:57.754967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f790719f3f1c'
down_revision: Union[str, None] = '72bdfc6dc429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infusion_chairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chair_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infusion_chairs_id'), 'infusion_chairs', ['id'], unique=False)
    op.create_foreign_key(None, 'slot_availabilities', 'infusion_chairs', ['chair_id'], ['id'], ondelete='CASCADE')
    op.add_column('treatment_plans', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_plans', 'duration_minutes')
    op.drop_constraint(None, 'slot_availabilities', type_='foreignkey')
    op.drop_index(op.f('ix_infusion_chairs_id'), table_name='infusion_chairs')
    op.drop_table('infusion_chairs')
    # ### end Alembic commands ###
